services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bookit
      POSTGRES_PASSWORD: bookit_pass
      POSTGRES_DB: bookit_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: